# Generated by Django 3.2.10 on 2021-12-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
