# Generated by Django 3.2.10 on 2021-12-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_data_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
